### ISSUE TITLE
error running soundflo

### ISSUE THREAD

**Issue by rdtor** [jonnor/sndflo#13]
ERROR: duplicate Class found: 'SndFloUiConnection' 
/home/s***/.local/share/SuperCollider/Extensions/sndflo/classes/Runtime.sc
/home/s***/.local/share/SuperCollider/Extensions/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/classes/Runtime.sc

ERROR: duplicate Class found: 'SndFloRuntime' 
/home/s***/.local/share/SuperCollider/Extensions/sndflo/classes/Runtime.sc
/home/s***/.local/share/SuperCollider/Extensions/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/classes/Runtime.sc

ERROR: duplicate Class found: 'SndFlo' 
/home/s***/.local/share/SuperCollider/Extensions/sndflo/classes/SndFlo.sc
/home/s***/.local/share/SuperCollider/Extensions/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/classes/SndFlo.sc

terminate called after throwing an instance of 'boost::filesystem::filesystem_error'

  what():  boost::filesystem::status: Too many levels of symbolic links: "/home/s***/.local/share/SuperCollider/Extensions/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo/sndflo"

/home/s***/Programs/sndflo/sndflo.coffee:345
        throw err;
        ^

Error: Runtime exited with non-zero code: null :SIGABRT
    at ChildProcess.<anonymous> (/home/s***/Programs/sndflo/sndflo.coffee:115:26)
    at ChildProcess.emit (events.js:193:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)

**Comment by jonnor** [comment]
Those paths look mighty crazy. Do you have some symlinks in there for sndflo?

**Comment by rdtor** [comment]
Hi thx for the reply, i reinstalled it using quarks to install the sndflo and got it running in the terminal here is my output

SuperCollider 3 server ready.

JackDriver: max output latency 46.4 ms

Requested notification messages from server 'localhost'

localhost: server process's maxLogins (1) matches with my options.

localhost: keeping clientID (0) as confirmed by server process.

Shared memory server interface initialized
sndflo-runtime starting

sndflo-runtime running on port 57120

internal port 57120
Listening at WebSocket port 3569 
OSC send/receive ports:  57120 57122 Open in Flowhub:  http://app.flowhub.io/#runtime/endpoint?protocol%3Dwebsocket%26address%3Dws%3A%2F%2Flocalhost%3A3569
Registered with Flowhub, should be accessible in UI

However i dont see an components in the flow hub its empty.

Edit : i did got ruuning the components were under the name of project, Are there just four components?
